dist: trusty
language: rust

rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
  - rust: nightly
  fast_finish: true

before_install:
  - sudo apt-get install -qq libegl1-mesa-dev libgles2-mesa-dev
  - sudo apt-get install -qq libsdl2-dev
